/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Legge la configurazione corrente
         * @description Restituisce la configurazione runtime attualmente applicata.
         */
        get: operations["getConfiguration"];
        /**
         * Aggiorna la configurazione corrente
         * @description Sostituisce la configurazione runtime e la persiste nel file JSON.
         *     L'aggiornamento è immediato e non richiede il riavvio.
         *
         *     Il campo `database_path` è bootstrap-only e deve rimanere invariato
         *     rispetto al valore usato all'avvio. La richiesta deve contenere una
         *     chiave attualmente autorizzata; non è possibile usare questa operazione
         *     per aggiungere la prima chiave quando `api_keys` è vuoto.
         *
         */
        put: operations["updateConfiguration"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/calendario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Legge il calendario settimanale
         * @description Restituisce i sette giorni del calendario con gli intervalli configurati.
         */
        get: operations["getCalendar"];
        /**
         * Aggiorna il calendario settimanale
         * @description Sostituisce e persiste il calendario. Il payload deve contenere
         *     esattamente i sette giorni canonici. Gli intervalli dello stesso giorno
         *     non possono sovrapporsi e `ora_inizio` deve precedere `ora_fine`.
         *     Gli orari sono interpretati in UTC; la fine dell'intervallo è esclusa.
         *
         */
        put: operations["updateCalendar"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Legge il log dei cicli di polling
         * @description Restituisce i record ordinati per timestamp crescente. Senza parametri
         *     viene usato il giorno corrente in UTC. `da` e `a` sono inclusivi a
         *     livello di data: il range effettivo è `[da 00:00:00Z, a + 1 giorno
         *     00:00:00Z)`.
         *
         */
        get: operations["getPollingLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/log/errori": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Legge il log degli errori
         * @description Restituisce gli errori ordinati per timestamp crescente. I parametri
         *     hanno la stessa semantica di `GET /log` e sono interpretati in UTC.
         *
         */
        get: operations["getErrorLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stato": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Legge lo stato corrente del termostato
         * @description Legge in tempo reale la temperatura dal sensore e lo stato dal relay.
         *     `temperatura_target` è il target risolto dalla configurazione al momento
         *     della richiesta: override se attivo, altrimenti intervallo calendario
         *     UTC corrente. È `null` quando non esiste alcun target attivo.
         *
         */
        get: operations["getCurrentState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actuator/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verifica lo stato applicativo
         * @description Endpoint Spring Boot Actuator esposto dalla configurazione applicativa.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actuator/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Legge le informazioni applicative
         * @description Endpoint Spring Boot Actuator `info`, esposto ma senza dettagli custom obbligatori.
         */
        get: operations["getActuatorInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actuator/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Elenca i nomi delle metriche */
        get: operations["listMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actuator/metrics/{requiredMetricName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Legge una metrica */
        get: operations["getMetric"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/temperature": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Legge la temperatura simulata
         * @description Disponibile solo con il profilo `mock`. È il contratto usato dal client
         *     interno del sensore; in produzione questo endpoint è sostituito dall'URL
         *     del dispositivo configurato in `sensore_url`.
         *
         */
        get: operations["getMockTemperature"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/relay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Legge lo stato del relay simulato
         * @description Disponibile solo con il profilo `mock`.
         */
        get: operations["getMockRelayState"];
        put?: never;
        /**
         * Invia un comando al relay simulato
         * @description Disponibile solo con il profilo `mock`; aggiorna lo stato mantenuto dal dispositivo simulato.
         */
        post: operations["commandMockRelay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mock/temperature": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Imposta la temperatura simulata
         * @description Disponibile solo con il profilo `mock`; endpoint di controllo dello scenario E2E.
         */
        put: operations["setMockTemperature"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mock/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Legge lo stato completo del dispositivo simulato
         * @description Disponibile solo con il profilo `mock`; utile per le asserzioni E2E.
         */
        get: operations["getMockState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mock/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ripristina lo stato iniziale del mock
         * @description Disponibile solo con il profilo `mock`; ripristina temperatura e relay dai valori di configurazione del mock.
         */
        post: operations["resetMockState"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Configurazione runtime completa. I valori numerici di temperatura
         *     devono avere una sola cifra decimale. Se `override_attivo` è true,
         *     `temperatura_override` è obbligatoria; se è false può essere null.
         *      */
        SystemConfiguration: {
            /**
             * Format: double
             * @description Isteresi di attivazione in °C.
             * @example 0.3
             */
            soglia_attivazione: number;
            /**
             * @description Abilita l'override manuale del target calendario.
             * @example false
             */
            override_attivo: boolean;
            /**
             * Format: double
             * @description Target manuale in °C; obbligatorio quando `override_attivo` è true.
             * @example 20.5
             */
            temperatura_override: number | null;
            /**
             * Format: int32
             * @description Intervallo del ciclo di controllo in secondi.
             * @example 60
             */
            intervallo_polling_secondi: number;
            /**
             * Format: int32
             * @description Soglia di errori consecutivi prima della messa in sicurezza.
             * @example 3
             */
            max_errori_consecutivi: number;
            /**
             * Format: int32
             * @description Giorni di conservazione dei log.
             * @example 30
             */
            retention_log_giorni: number;
            /**
             * Format: uri
             * @description URL base del servizio ntfy.
             * @example https://ntfy.sh
             */
            ntfy_url: string;
            /**
             * @description Topic ntfy usato per le notifiche.
             * @example sliverd
             */
            ntfy_topic: string;
            /**
             * @description Abilita le notifiche informative di accensione e spegnimento.
             * @example false
             */
            debug_mode: boolean;
            /**
             * Format: uri
             * @description URL base del sensore REST esterno.
             * @example http://sensore.local
             */
            sensore_url: string;
            /**
             * Format: uri
             * @description URL base del relay REST esterno.
             * @example http://relay.local
             */
            relay_url: string;
            /**
             * @description Percorso del database SQLite; bootstrap-only.
             * @example ./data/termostato.db
             */
            database_path: string;
            /**
             * @description Elenco delle API-key autorizzate. Lista vuota significa fail-closed.
             * @example [
             *       "e2e-test-key"
             *     ]
             */
            api_keys: string[];
        };
        /** @description Calendario settimanale con esattamente i sette giorni canonici. */
        CalendarDocument: {
            giorni: {
                lunedi: components["schemas"]["CalendarIntervals"];
                martedi: components["schemas"]["CalendarIntervals"];
                mercoledi: components["schemas"]["CalendarIntervals"];
                giovedi: components["schemas"]["CalendarIntervals"];
                venerdi: components["schemas"]["CalendarIntervals"];
                sabato: components["schemas"]["CalendarIntervals"];
                domenica: components["schemas"]["CalendarIntervals"];
            };
        };
        /** @description Intervalli ordinati automaticamente per ora di inizio e non sovrapposti. */
        CalendarIntervals: components["schemas"]["TimeInterval"][];
        TimeInterval: {
            /**
             * @description Ora UTC di inizio, inclusiva. Sono accettati `HH:mm` e `HH:mm:ss`.
             * @example 06:00
             */
            ora_inizio: string;
            /**
             * @description Ora UTC di fine, esclusiva; deve essere successiva a `ora_inizio`.
             * @example 08:00
             */
            ora_fine: string;
            /**
             * Format: double
             * @description Temperatura target in °C con una cifra decimale.
             * @example 20.5
             */
            temperatura_target: number;
        };
        TemperatureReading: {
            /**
             * Format: double
             * @description Temperatura in °C, normalizzata a una cifra decimale.
             * @example 19
             */
            temperatura: number;
        };
        RelayCommand: {
            /**
             * @description `true` accende il relay; `false` lo spegne.
             * @example true
             */
            acceso: boolean;
        };
        RelayStateResponse: {
            /**
             * @description Stato corrente del relay.
             * @example false
             */
            acceso: boolean;
        };
        MockStateResponse: {
            /**
             * Format: double
             * @description Temperatura corrente del dispositivo simulato in °C.
             * @example 19
             */
            temperatura: number;
            /**
             * @description Stato corrente del relay simulato.
             * @example false
             */
            relay_acceso: boolean;
        };
        PollingLogRecord: {
            /**
             * Format: int64
             * @example 42
             */
            id: number;
            /**
             * Format: date-time
             * @description Timestamp del ciclo in UTC.
             * @example 2026-09-04T10:00:00.000000000Z
             */
            data_ora: string;
            /** @example true */
            caldaia_accesa: boolean;
            /**
             * Format: double
             * @example 19
             */
            temperatura_rilevata: number;
            /**
             * Format: double
             * @description Target risolto; null quando non è attivo alcun intervallo o override.
             * @example 20.5
             */
            temperatura_target: number | null;
            /** @example false */
            override_attivo: boolean;
            /**
             * Format: double
             * @example null
             */
            temperatura_override: number | null;
        };
        ErrorLogRecord: {
            /**
             * Format: int64
             * @example 7
             */
            id: number;
            /**
             * Format: date-time
             * @description Timestamp dell'errore in UTC.
             * @example 2026-09-04T10:00:00.000000000Z
             */
            data_ora: string;
            /**
             * @description Categoria tecnica dell'errore.
             * @example READ_TEMP
             */
            tipo_errore: string;
            /**
             * @description Stato della caldaia se disponibile.
             * @example false
             */
            caldaia_accesa: boolean | null;
            /**
             * Format: double
             * @description Ultima temperatura disponibile, se presente.
             * @example null
             */
            temperatura_rilevata: number | null;
            /**
             * Format: int32
             * @example 1
             */
            num_errori_consecutivi: number;
        };
        ApiError: {
            /**
             * Format: date-time
             * @description Istante UTC della risposta di errore.
             */
            timestamp: string;
            /**
             * Format: int32
             * @example 400
             */
            status: number;
            /** @example Bad Request */
            error: string;
            /** @example Payload non valido */
            message: string;
        };
        UnauthorizedError: {
            /** @example API key mancante o non valida */
            error: string;
        };
        ActuatorHealth: {
            /**
             * @description Stato aggregato dell'applicazione.
             * @example UP
             * @enum {string}
             */
            status: "UP" | "DOWN" | "OUT_OF_SERVICE" | "UNKNOWN";
        } & {
            [key: string]: unknown;
        };
        ActuatorMetricNames: {
            /** @example [
             *       "jvm.memory.used",
             *       "process.uptime"
             *     ] */
            names: string[];
        };
        ActuatorMetric: {
            /** @example process.uptime */
            name: string;
            /** @example The uptime of the Java Virtual Machine */
            description?: string | null;
            /** @example seconds */
            baseUnit?: string | null;
            measurements: components["schemas"]["ActuatorMeasurement"][];
            availableTags?: {
                [key: string]: unknown;
            }[];
        } & {
            [key: string]: unknown;
        };
        ActuatorMeasurement: {
            /** @example VALUE */
            statistic: string;
            /**
             * Format: double
             * @example 123.45
             */
            value: number;
        };
    };
    responses: {
        /** @description API-key assente, vuota o non autorizzata */
        Unauthorized: {
            headers: {
                /** @description Schema di autenticazione richiesto dal backend */
                "WWW-Authenticate"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["UnauthorizedError"];
            };
        };
        /** @description Body o parametri non validi */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Errore interno o impossibilità di persistere la modifica */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        /**
         * @description Data iniziale inclusiva in UTC. Default: giorno corrente UTC, oppure il valore di `a` se `da` è assente.
         * @example 2026-09-01
         */
        FromDate: string;
        /**
         * @description Data finale inclusiva in UTC. Default: giorno corrente UTC.
         * @example 2026-09-04
         */
        ToDate: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getConfiguration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configurazione corrente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemConfiguration"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateConfiguration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /** @example {
                 *       "soglia_attivazione": 0.3,
                 *       "override_attivo": true,
                 *       "temperatura_override": 20.5,
                 *       "intervallo_polling_secondi": 60,
                 *       "max_errori_consecutivi": 3,
                 *       "retention_log_giorni": 30,
                 *       "ntfy_url": "https://ntfy.sh",
                 *       "ntfy_topic": "sliverd",
                 *       "debug_mode": false,
                 *       "sensore_url": "http://sensore.local",
                 *       "relay_url": "http://relay.local",
                 *       "database_path": "./data/termostato.db",
                 *       "api_keys": [
                 *         "sostituire-con-una-chiave-segreta"
                 *       ]
                 *     } */
                "application/json": components["schemas"]["SystemConfiguration"];
            };
        };
        responses: {
            /** @description Configurazione aggiornata e persistita */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemConfiguration"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getCalendar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Calendario corrente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarDocument"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateCalendar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /** @example {
                 *       "giorni": {
                 *         "lunedi": [],
                 *         "martedi": [],
                 *         "mercoledi": [],
                 *         "giovedi": [
                 *           {
                 *             "ora_inizio": "06:00",
                 *             "ora_fine": "08:00",
                 *             "temperatura_target": 20.5
                 *           }
                 *         ],
                 *         "venerdi": [],
                 *         "sabato": [],
                 *         "domenica": []
                 *       }
                 *     } */
                "application/json": components["schemas"]["CalendarDocument"];
            };
        };
        responses: {
            /** @description Calendario aggiornato e persistito */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarDocument"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getPollingLogs: {
        parameters: {
            query?: {
                /**
                 * @description Data iniziale inclusiva in UTC. Default: giorno corrente UTC, oppure il valore di `a` se `da` è assente.
                 * @example 2026-09-01
                 */
                da?: components["parameters"]["FromDate"];
                /**
                 * @description Data finale inclusiva in UTC. Default: giorno corrente UTC.
                 * @example 2026-09-04
                 */
                a?: components["parameters"]["ToDate"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Record del log di polling */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollingLogRecord"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getErrorLogs: {
        parameters: {
            query?: {
                /**
                 * @description Data iniziale inclusiva in UTC. Default: giorno corrente UTC, oppure il valore di `a` se `da` è assente.
                 * @example 2026-09-01
                 */
                da?: components["parameters"]["FromDate"];
                /**
                 * @description Data finale inclusiva in UTC. Default: giorno corrente UTC.
                 * @example 2026-09-04
                 */
                a?: components["parameters"]["ToDate"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Record del log degli errori */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorLogRecord"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getCurrentState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stato corrente del termostato */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: double
                         * @description Temperatura rilevata dal sensore in °C.
                         * @example 19
                         */
                        temperatura: number;
                        /**
                         * Format: double
                         * @description Target configurato e attivo in °C; null senza target.
                         * @example 20.5
                         */
                        temperatura_target: number | null;
                        /**
                         * @description Stato letto direttamente dal relay.
                         * @example false
                         */
                        relay_acceso: boolean;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stato applicativo disponibile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActuatorHealth"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getActuatorInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Informazioni applicative; può essere un oggetto vuoto */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Nomi delle metriche disponibili */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActuatorMetricNames"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMetric: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Nome della metrica restituito da `GET /actuator/metrics`.
                 * @example process.uptime
                 */
                requiredMetricName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Valore e misurazioni della metrica */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActuatorMetric"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Metrica inesistente */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getMockTemperature: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Temperatura corrente del sensore simulato */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemperatureReading"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Profilo mock non attivo */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMockRelayState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stato corrente del relay simulato */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelayStateResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Profilo mock non attivo */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    commandMockRelay: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelayCommand"];
            };
        };
        responses: {
            /** @description Comando applicato; nessun body nella risposta */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Profilo mock non attivo */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setMockTemperature: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /** @example {
                 *       "temperatura": 21
                 *     } */
                "application/json": components["schemas"]["TemperatureReading"];
            };
        };
        responses: {
            /** @description Nuova lettura del sensore simulato */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemperatureReading"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Profilo mock non attivo */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMockState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Temperatura e stato relay simulati */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MockStateResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Profilo mock non attivo */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resetMockState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stato mock ripristinato */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MockStateResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Profilo mock non attivo */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
